# Generated by Django 5.0.3 on 2024-04-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='prog_namme',
            new_name='prog_name',
        ),
    ]
